name: resident_alert
description: แอปลูกบ้าน — รับแจ้งเตือนผู้เข้าหมู่บ้านแบบเรียลไทม์
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4

  # HTTP
  http: ^1.2.2

  # Local storage
  shared_preferences: ^2.2.3

  # UUID
  uuid: ^4.4.0

  # Font
  google_fonts: ^6.3.1

  # Permission handler
  permission_handler: ^11.3.1

  # Intl
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
